[package]
name = "uefi-logger"
version = "0.2.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
uefi = { path = ".." }
log = { version = "0.4", default-features = false }
