language: rust
rust:
  - nightly

python:
  - "3.6"

dist: trusty
sudo: false

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

before_install:
  - cargo install xargo || true

script:
  - cd tests
  - python3 -m build build
