[package]
name = "uefi"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
readme = "README.md"
publish = false
edition = "2018"

[dependencies]
bitflags = "1"
ucs2 = "0.1"

[workspace]
members = [
    "uefi-test-runner",
    "uefi-logger",
    "uefi-alloc",
    "uefi-services",
    "uefi-exts",
]
