[package]
name = "uefi"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
readme = "README.md"
publish = false

[dependencies]
bitflags = "1"

[workspace]
members = [
    "uefi-test-runner",
    "uefi-logger",
    "uefi-alloc",
    "uefi-services",
    "uefi-utils",
]
