[package]
name = "uefi-utils"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
publish = false

[dependencies]
uefi = { path = ".." }
uefi-services = { path = "../uefi-services" }
